#!/usr/bin/env bash
# One-time setup for a fresh Ubuntu instance. Run it once, by hand, as the user
# the deploy workflow will connect as.
#
# It does not deploy anything. It prepares the place a deploy lands: Docker, the
# directory, the secrets file, and the nightly backup. Afterwards every release
# goes through the Deploy action and nobody needs to log in again.
set -euo pipefail

DEPLOY_PATH="${DEPLOY_PATH:-/opt/timetracker}"
BACKUP_DIR="${BACKUP_DIR:-/var/backups/ttcloud}"

say() { printf '\n\033[1m%s\033[0m\n' "$*"; }

if [ "$(id -u)" -eq 0 ]; then
  echo "Run this as the deploy user, not root — the workflow connects as that" >&2
  echo "user and it needs to own $DEPLOY_PATH." >&2
  exit 1
fi

say "Installing Docker"
if ! command -v docker >/dev/null; then
  curl -fsSL https://get.docker.com | sudo sh
  # So the deploy workflow can run compose without sudo. Takes effect on the
  # next login, which is why the workflow's own connection is a fresh one.
  sudo usermod -aG docker "$USER"
else
  echo "already installed"
fi

say "Creating $DEPLOY_PATH"
sudo mkdir -p "$DEPLOY_PATH"
sudo chown -R "$USER:$USER" "$DEPLOY_PATH"

say "Writing $DEPLOY_PATH/.env"
if [ -f "$DEPLOY_PATH/.env" ]; then
  echo "already exists — left alone. Editing it by hand is expected."
else
  # Generated here rather than typed, and never leaving the instance. These are
  # the two values that must not be guessable and must not live in the repo or
  # in a CI secret store.
  cat > "$DEPLOY_PATH/.env" <<ENV
# Generated by bootstrap.sh. This file is the production configuration and is
# deliberately NOT in the repository — the deploy workflow excludes it from
# every sync, so editing it here is safe and edits survive releases.
POSTGRES_USER=ttcloud
POSTGRES_PASSWORD=$(openssl rand -base64 33 | tr -d '/+=' | head -c 40)
POSTGRES_DB=ttcloud
SECRET_KEY=$(openssl rand -base64 48 | tr -d '/+=' | head -c 64)

# The domain Caddy obtains a certificate for. It must already resolve to this
# instance or the certificate request fails and the site stays down.
DOMAIN=CHANGE-ME.example.com

# Screen captures. Leave S3_BUCKET blank to keep them on this disk instead.
S3_BUCKET=
S3_PREFIX=screenshots
AWS_REGION=eu-west-1

# Per-person report delivery. Blank means reports are skipped, not retried.
SMTP_HOST=
SMTP_PORT=465
SMTP_USER=
SMTP_PASSWORD=
MAIL_FROM=

DEFAULT_TIMEZONE=Africa/Nairobi
ENV
  chmod 600 "$DEPLOY_PATH/.env"
  echo "written with a generated password and secret key"
fi

say "Nightly backup"
sudo mkdir -p "$BACKUP_DIR"
sudo chown -R "$USER:$USER" "$BACKUP_DIR"
CRON="15 2 * * * cd $DEPLOY_PATH && docker compose -f docker-compose.prod.yml exec -T db sh -c 'BACKUP_DIR=/backups /backup.sh' >> /var/log/ttcloud-backup.log 2>&1"
if crontab -l 2>/dev/null | grep -q ttcloud-backup; then
  echo "already scheduled"
else
  ( crontab -l 2>/dev/null || true; echo "$CRON" ) | crontab -
  echo "scheduled for 02:15 daily"
fi

say "Done. Before the first deploy:"
cat <<NEXT
  1. Edit $DEPLOY_PATH/.env — set DOMAIN, and the SMTP and S3 values.
  2. Point that domain's A record at this instance's public address.
  3. Open ports 80 and 443 to the world, and 22 only to where you deploy from.
  4. Add this machine's host key to the SSH_KNOWN_HOSTS secret in GitHub:

       ssh-keyscan -t ed25519 $(hostname -I | awk '{print $1}')

     Read it here and paste it there — the workflow pins it rather than
     trusting whatever answers on the day.
  5. Run the Deploy action.

  Nothing is created for you in AWS: the instance, the DNS record, the S3
  bucket and its IAM user are made once by hand. docs/DEPLOY.md lists them.
NEXT
