"""consent records and pause control

Revision ID: 97db7417aa4a
Revises: 0f0b66e2220e
Create Date: 2026-08-26 21:09:32.695691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97db7417aa4a'
down_revision: Union[str, None] = '0f0b66e2220e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'policy_version', name='uq_consent_user_version')
    )
    op.add_column('user_settings', sa.Column('tracking_paused_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_settings', sa.Column('pause_reason', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'pause_reason')
    op.drop_column('user_settings', 'tracking_paused_until')
    op.drop_table('consents')
    # ### end Alembic commands ###
