"""client_uuid for idempotent agent uploads

Revision ID: c83c0d1503a7
Revises: cc2d7f8bcc93
Create Date: 2026-08-26 16:53:58.503427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c83c0d1503a7'
down_revision: Union[str, None] = 'cc2d7f8bcc93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_usage', sa.Column('client_uuid', sa.UUID(), nullable=False))
    op.create_unique_constraint('uq_app_usage_client_uuid', 'app_usage', ['user_id', 'client_uuid'])
    op.add_column('idle_periods', sa.Column('client_uuid', sa.UUID(), nullable=False))
    op.create_unique_constraint('uq_idle_client_uuid', 'idle_periods', ['user_id', 'client_uuid'])
    op.add_column('sessions', sa.Column('client_uuid', sa.UUID(), nullable=False))
    op.create_unique_constraint('uq_sessions_client_uuid', 'sessions', ['user_id', 'client_uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sessions_client_uuid', 'sessions', type_='unique')
    op.drop_column('sessions', 'client_uuid')
    op.drop_constraint('uq_idle_client_uuid', 'idle_periods', type_='unique')
    op.drop_column('idle_periods', 'client_uuid')
    op.drop_constraint('uq_app_usage_client_uuid', 'app_usage', type_='unique')
    op.drop_column('app_usage', 'client_uuid')
    # ### end Alembic commands ###
