"""initial multi-user schema

Revision ID: cc2d7f8bcc93
Revises: 
Create Date: 2026-08-26 16:42:06.362012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc2d7f8bcc93'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('worker', 'admin')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('activity_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('draft', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('tracked_seconds', sa.Integer(), nullable=False),
    sa.Column('activities', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('answered_seconds', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'confirmed', 'skipped')", name='ck_activity_logs_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'log_date', name='uq_activity_logs_user_date')
    )
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_devices_user', 'devices', ['user_id'], unique=False)
    op.create_table('idle_periods',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_idle_user_started', 'idle_periods', ['user_id', 'started_at'], unique=False)
    op.create_table('report_sends',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('period_key', sa.String(length=16), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.CheckConstraint("kind IN ('weekly', 'monthly')", name='ck_report_sends_kind'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'kind', 'period_key', name='uq_report_sends_period')
    )
    op.create_table('sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project', sa.String(length=120), nullable=False),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ended_at IS NULL OR ended_at >= started_at', name='ck_sessions_order'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_user_started', 'sessions', ['user_id', 'started_at'], unique=False)
    op.create_index('uq_sessions_one_open_per_user', 'sessions', ['user_id'], unique=True, postgresql_where=sa.text('ended_at IS NULL'))
    op.create_table('user_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('day_goal_seconds', sa.Integer(), nullable=False),
    sa.Column('week_goal_seconds', sa.Integer(), nullable=False),
    sa.Column('idle_threshold_seconds', sa.Integer(), nullable=False),
    sa.Column('screenshot_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('screenshots_enabled', sa.Boolean(), nullable=False),
    sa.Column('prompt_start_hour', sa.Integer(), nullable=False),
    sa.Column('prompt_end_hour', sa.Integer(), nullable=False),
    sa.Column('weekly_send_weekday', sa.Integer(), nullable=False),
    sa.Column('weekly_send_hour', sa.Integer(), nullable=False),
    sa.Column('monthly_send_hour', sa.Integer(), nullable=False),
    sa.Column('reports_enabled', sa.Boolean(), nullable=False),
    sa.Column('streams', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('catch_all_stream', sa.String(length=64), nullable=False),
    sa.Column('private_labels', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('research_labels', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.CheckConstraint('idle_threshold_seconds > 0', name='ck_settings_idle'),
    sa.CheckConstraint('prompt_end_hour BETWEEN 1 AND 24', name='ck_settings_prompt_end'),
    sa.CheckConstraint('prompt_start_hour BETWEEN 0 AND 23', name='ck_settings_prompt_start'),
    sa.CheckConstraint('weekly_send_weekday BETWEEN 0 AND 6', name='ck_settings_weekday'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('app_usage',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=True),
    sa.Column('app_name', sa.String(length=120), nullable=False),
    sa.Column('window_title', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_app_usage_user_started', 'app_usage', ['user_id', 'started_at'], unique=False)
    op.create_table('screenshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('full_key', sa.String(length=512), nullable=False),
    sa.Column('thumb_key', sa.String(length=512), nullable=True),
    sa.Column('bytes_full', sa.Integer(), nullable=True),
    sa.Column('full_deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_screenshots_user_captured', 'screenshots', ['user_id', 'captured_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_screenshots_user_captured', table_name='screenshots')
    op.drop_table('screenshots')
    op.drop_index('ix_app_usage_user_started', table_name='app_usage')
    op.drop_table('app_usage')
    op.drop_table('user_settings')
    op.drop_index('uq_sessions_one_open_per_user', table_name='sessions', postgresql_where=sa.text('ended_at IS NULL'))
    op.drop_index('ix_sessions_user_started', table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('report_sends')
    op.drop_index('ix_idle_user_started', table_name='idle_periods')
    op.drop_table('idle_periods')
    op.drop_index('ix_devices_user', table_name='devices')
    op.drop_table('devices')
    op.drop_table('activity_logs')
    op.drop_table('users')
    # ### end Alembic commands ###
