"""screenshot client_uuid

Revision ID: ee222892c8b6
Revises: 05bef9409b84
Create Date: 2026-08-26 20:29:01.556180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee222892c8b6'
down_revision: Union[str, None] = '05bef9409b84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screenshots', sa.Column('client_uuid', sa.UUID(), nullable=False))
    op.create_unique_constraint('uq_screenshots_client_uuid', 'screenshots', ['user_id', 'client_uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_screenshots_client_uuid', 'screenshots', type_='unique')
    op.drop_column('screenshots', 'client_uuid')
    # ### end Alembic commands ###
